In [16]:
import pandas as pd
import numpy as np
csv_list = pd.read_csv("D:\\大三\\数学建模\\C题\\sheet2.csv")
csv_list=csv_list.fillna(0)
csv_array = np.array(csv_list)

# csv_array = csv_list.values
csv_array = csv_array[:,1:-5]
# print(csv_array.shape)
# nan_ = csv_array[0][2]
# print(type(csv_array[0][2]))
# print(np.where(csv_array==nan_))
# print()
# print(csv_array)


[[69.33 0.0 9.99 6.32 0.87 3.93 1.74 3.87 0.0 0.0 1.17 0.0 0.0 0.39]
 [36.28 0.0 1.05 2.34 1.18 5.73 1.86 0.26 47.43 0.0 3.57 0.19 0.0 0.0]
 [87.05 0.0 5.19 2.01 0.0 4.06 0.0 0.78 0.25 0.0 0.66 0.0 0.0 0.0]
 [61.71 0.0 12.37 5.87 1.11 5.5 2.16 5.09 1.41 2.86 0.7 0.1 0.0 0.0]
 [65.88 0.0 9.67 7.12 1.56 6.44 2.06 2.18 0.0 0.0 0.79 0.0 0.0 0.36]
 [61.58 0.0 10.95 7.35 1.77 7.5 2.62 3.27 0.0 0.0 0.94 0.06 0.0 0.47]
 [67.65 0.0 7.37 0.0 1.98 11.15 2.39 2.51 0.2 1.38 4.18 0.11 0.0 0.0]
 [59.81 0.0 7.68 5.41 1.73 10.05 6.04 2.18 0.35 0.97 4.5 0.12 0.0 0.0]
 [92.63 0.0 0.0 1.07 0.0 1.98 0.17 3.24 0.0 0.0 0.61 0.0 0.0 0.0]
 [20.14 0.0 0.0 1.48 0.0 1.34 0.0 10.41 28.68 31.23 3.59 0.37 0.0 2.58]
 [4.61 0.0 0.0 3.19 0.0 1.11 0.0 3.14 32.45 30.62 7.56 0.53 0.0 15.03]
 [95.02 0.0 0.59 0.62 0.0 1.32 0.32 1.55 0.0 0.0 0.35 0.0 0.0 0.0]
 [96.77 0.0 0.92 0.21 0.0 0.81 0.26 0.84 0.0 0.0 0.0 0.0 0.0 0.0]
 [33.59 0.0 0.21 3.51 0.71 2.69 0.0 4.93 25.39 14.61 9.38 0.37 0.0 0.0]
 [94.29 0.0 1.01 0.72 0.0 1.4

In [3]:
from sklearn.metrics import silhouette_score, silhouette_samples
from sklearn.cluster import KMeans
from matplotlib import pyplot as plt

for i in range(2,9):
    n_clusters = i
    estimator = KMeans(n_clusters=n_clusters)#构造聚类器
    estimator.fit(riders_cp_time)#聚类
    label_pred = estimator.labels_ #获取聚类标签
    centroids = estimator.cluster_centers_ #获取聚类中心
    inertia = estimator.inertia_ # 获取聚类准则的总和

    sc = silhouette_score(riders_cp_time, label_pred)


    print(n_clusters,inertia,sc)

2 114812527.17968786 0.4175384366211063
3 76859874.094819 0.41162239863009725
4 60530027.88862597 0.35975653114327416
5 47577335.62984525 0.3731799247237591
6 41140847.54906556 0.31906065657385047
7 36200340.47945531 0.3273171801425904
8 32752424.029814895 0.29547764566073426


In [4]:
# 选择5
# 1 Pursuiter 2 All-Rounder 3 Sprinter 4 Time Trialist, Climber
n_clusters = 5
estimator = KMeans(n_clusters=n_clusters)#构造聚类器
estimator.fit(riders_cp_time)#聚类
label_pred = estimator.labels_ #获取聚类标签
centroids = estimator.cluster_centers_ #获取聚类中心
inertia = estimator.inertia_ # 获取聚类准则的总和

sc = silhouette_score(riders_cp_time, label_pred)

print(centroids)

clusters = np.unique(label_pred)

[[ 941.19598165  695.13234455  358.99521774  332.28253505  307.44367976
   288.39466525  281.4748929   264.21087219  247.49834239]
 [1901.00501991  878.73116274  414.71602377  381.76293302  350.78355094
   324.31733887  314.89494953  295.75515736  280.51163255]
 [ 574.8138017   428.85279128  266.14709355  250.35494411  234.74291929
   222.78997064  218.21889972  206.18612085  193.81168794]
 [1277.82357597  920.98860597  430.47236961  391.71529357  357.00532262
   332.33448148  324.05860033  305.02784911  286.58838128]
 [1409.42857143 2319.22190429  457.37500143  389.24285714  354.48499857
   323.10863143  318.94642714  297.23184571  283.99361   ]]


In [6]:
#%matplotlib
# 7="Others" 305="Time Trialist/Climber" 106="Sprinter" 297="Pursuiter" 141=“All-Rounder”
type_list = []
fig = plt.figure()
ax1 = plt.axes(projection='3d')

mark = ['or', 'ob', 'og', 'ok', '^r', '+r', 'sr', 'dr', '<r', 'pr']
cp_time_list = np.array([1,15,120,180,300,480,600,1200,1800])
mean_cp_time_list = []
type_num_list = []
for cluster in clusters:
    row_ix = np.where(label_pred == cluster)[0]
    type_num_list.append(len(row_ix))
    if len(row_ix)==7:
        type_list.append("Others")
    elif  len(row_ix)==305:
        type_list.append("Time_Trialist_Climber")
    elif  len(row_ix)==106:
        type_list.append("Sprinter") 
    elif  len(row_ix)==297:
        type_list.append("Pursuiter") 
    elif  len(row_ix)==141:
        type_list.append("All_Rounder") 
    print(cluster,type_list[cluster],len(row_ix))
    x = [float(i) for i in riders_cp_time[row_ix, 0]]
    y = [float(i) for i in riders_cp_time[row_ix, 2]]
    z = [float(i) for i in riders_cp_time[row_ix, 8]]
    ax1.scatter(x,y,z,mark[cluster],label=type_list[cluster])

ax1.title.set_text('Kmeans Result')
ax1.set_xlabel('1s_critical_power')
ax1.set_ylabel('2m_critical_power')
ax1.set_zlabel('30m_critical_power')
plt.show()
fig.savefig('Kmeans_%d_res.png'%(n_clusters),dpi=600)

Using matplotlib backend: Qt5Agg
0 Pursuiter 297
1 Sprinter 106
2 All_Rounder 141
3 Time_Trialist_Climber 305
4 Others 7


In [20]:
# print "Time Trialist/Climber"
for i in range(len(clusters)):
    id_type_data = {
        type_list[i]:list(riders_id[np.where(label_pred == i)]) 
    }
    id_type_data = pd.DataFrame(id_type_data)
    id_type_data.to_csv('%s_id.csv'%(type_list[i]),mode='a',index=False,header=False)

In [5]:
# 男女 柱状图
male_list = np.zeros(5)
female_list = np.zeros(5)
for cluster in clusters:
    row_ix = np.where(label_pred == cluster)[0]
    res_male = np.where((riders_gender[row_ix]=='M'))[0]
    res_female = np.where((riders_gender[row_ix]=='F'))[0]
    male_list[cluster] = len(res_male)
    female_list[cluster] = len(res_female)

fig = plt.figure()
width_1 = 0.4
plt.bar(np.arange(len(male_list)),male_list,width=width_1,tick_label=type_list,label ="male")

plt.bar(np.arange(len(female_list))+width_1,female_list,width=width_1,label="female")
plt.legend()
plt.xlabel('Number')
plt.ylabel('Rider Type')
plt.show()

In [12]:
# 男女 饼图
male_list = np.zeros(5)
female_list = np.zeros(5)
for cluster in clusters:
    row_ix = np.where(label_pred == cluster)[0]
    res_male = np.where((riders_gender[row_ix]=='M'))[0]
    res_female = np.where((riders_gender[row_ix]=='F'))[0]
    male_list[cluster] = len(res_male)
    female_list[cluster] = len(res_female)

fig = plt.figure()
ax1, ax2 = fig.subplots(1, 2, sharey=True)
male_portion = [i*100.0/np.sum(male_list) for i in male_list]
female_portion = [i*100.0/np.sum(female_list) for i in female_list]
ax1.pie(male_portion,labels=type_list,autopct='%.2f%%',shadow=True)
ax2.pie(female_portion,labels=type_list,autopct='%.2f%%',shadow=True)

ax1.title.set_text('Male')
ax2.title.set_text('Female')
fig.savefig('gender_res.png',dpi=600)
plt.show()

In [7]:
from scipy import optimize
fig = plt.figure()
def power_fit(x, A, B):
    return A*np.power(x,B)
for cluster in clusters:
    x = np.linspace(cp_time_list[0],cp_time_list[-1],1000)
    if min(type_num_list)==type_num_list[cluster]:
        continue
    A, B = optimize.curve_fit(power_fit, cp_time_list, centroids[cluster])[0]
    y = A*np.power(x,B)
    plt.plot(np.log10(cp_time_list), centroids[cluster], '+',label='%s original'%(type_list[cluster]))
    plt.plot(np.log10(x), y,label='%s fit'%(type_list[cluster]))
plt.xlabel('log10(t) /s')
plt.ylabel('Critical Power')
# plt.legend(type_list) # 指定legend在图中的位置，类似象限的位置
plt.title('Critical Power Fit')
plt.show()

In [8]:
from scipy import optimize
fig = plt.figure()
x = np.linspace(cp_time_list[0],cp_time_list[-1],1000)
def test_fit(x, k0,k1,k2,k3,k4,k5,r1,r2):
    return (k0+k1*np.exp(-r1*x)+k2*np.exp(-r2*x))/(k3+k4*np.exp(-r1*x)+k5*np.exp(-r2*x))
for cluster in clusters:
    if min(type_num_list)==type_num_list[cluster]:
        continue
    k0,k1,k2,k3,k4,k5,r1,r2 = optimize.curve_fit(test_fit, cp_time_list, centroids[cluster], maxfev=100000)[0]
    y = (k0+k1*np.exp(-r1*x)+k2*np.exp(-r2*x))/(k3+k4*np.exp(-r1*x)+k5*np.exp(-r2*x))
    plt.plot(np.log10(cp_time_list), centroids[cluster], '+',label='%s original'%(type_list[cluster]))
    plt.plot(np.log10(x), y,label='%s fit'%(type_list[cluster]))
plt.xlabel('log10(t) /s')
plt.ylabel('Critical Power')
plt.legend()
plt.title('Power Profile')
fig.savefig('Power_Profile_res.png',dpi=600)
plt.show()

In [10]:
riders_w_mean = np.zeros(5)
riders_cp_mean = np.zeros(5)
riders_p_max_mean = np.zeros(5)

for cluster in clusters:
    row_ix = np.where(label_pred == cluster)[0]
    riders_w_mean[cluster] = np.mean(riders_w[row_ix])
    riders_cp_mean[cluster] = np.mean(riders_cp[row_ix])
    riders_p_max_mean[cluster] = np.mean(riders_p_max[row_ix])

print("riders_w_mean:",riders_w_mean)
print("riders_cp_mean:",riders_cp_mean)
print("riders_p_max_mean:",riders_p_max_mean)

riders_w_mean: [10977.23926744 19794.02689942 19963.03444886 16442.29129531
 20654.15383   ]
riders_cp_mean: [197.74341611 289.15519329 279.8295412  251.38581822 280.72573704]
riders_p_max_mean: [ 574.8138017  1277.83669072 1901.00501991  941.1488436  1409.42857143]
